### ISSUE TITLE
File format conversion

### ISSUE THREAD

**Issue by shubham7193** [siegert-lab/MorphOMICs#6]
Hi,
I have skeletons generated in Imaris, but I am unsure how to convert them to .swc format. The Matlab tool mentioned in the paper can extract the coordinates of the skeleton, but then how to convert those coordinate matrices to .swc file because Neuronland.org only takes files as input for conversion. 
Thanks in advance for your help.

**Comment by rcubero** [comment]
Hi,
You can use the Matlab scripts in https://github.com/rcubero/Matlab_Imaris_converter to convert
I have also placed the instructions there on how to run the codes.
I hope this helps.

Kind regards
